Updated index file with one course name and updated the yaml file with email trigger to manager for approval and deployment approval with changes in email

diff --git a/.github/workflows/deploytoGCP.yml b/.github/workflows/deploytoGCP.yml
--- a/.github/workflows/deploytoGCP.yml
+++ b/.github/workflows/deploytoGCP.yml
@@ -1,4 +1,4 @@
-name: Deploy Website to GCP
+name: Enterprise CI/CD Static Website to GCP (Approval Flow)
 
 on:
   push:
@@ -9,28 +9,169 @@ env:
   PROJECT_ID: githubaction-deploy-staticcode
   REGION: us-central1
   SERVICE_NAME: mywebsite
+  NODE_VERSION: '24'
+  PACKAGE_NAME: release.zip
+  MANAGER_EMAIL: yourmanager@email.com
+  MANAGER_NAME: Manager
 
 permissions:
   contents: read
   id-token: write
 
 jobs:
-  deploy:
+
+# -------------------------------------------------
+# JOB 1 - BUILD + VALIDATION + CHANGE SUMMARY
+# -------------------------------------------------
+  build:
+    runs-on: ubuntu-latest
+
+    outputs:
+      changes: ${{ steps.diff.outputs.changes }}
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v5
+
+      - name: Validate Required Files
+        run: |
+          test -f index.html || (echo "Missing index.html" && exit 1)
+          test -f css/style.css || (echo "Missing css/style.css" && exit 1)
+          test -f js/script.js || (echo "Missing js/script.js" && exit 1)
+
+      - name: Show Changed Files
+        id: diff
+        run: |
+          echo "changes<<EOF" >> $GITHUB_OUTPUT
+          git diff --name-only HEAD~1 HEAD >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+
+      - name: Zip Build Package
+        run: zip -r ${{ env.PACKAGE_NAME }} index.html css js
+
+      - name: Upload Build Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: website-build
+          path: ${{ env.PACKAGE_NAME }}
+
+# =================================================
+# JOB 2 - EMAIL APPROVAL REQUEST WITH CHANGES
+# =================================================
+  approval-mail:
+    name: Send Approval Email
+    needs: build
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
+      - name: Send Email
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          secure: false
+          username: ${{ secrets.MAIL_USERNAME }}
+          password: ${{ secrets.MAIL_PASSWORD }}
 
-      - uses: google-github-actions/auth@v2
+          subject: Production Deployment Approval Required | ${{ github.repository }}
+
+          to: ${{ env.MANAGER_EMAIL }}
+          from: ${{ secrets.MAIL_USERNAME }}
+
+          html_body: |
+            <html>
+            <body style="font-family:Arial, Helvetica, sans-serif; color:#333333; line-height:1.6;">
+
+            <h2 style="color:#0b5ed7;">Dear ${{ env.MANAGER_NAME }},</h2>
+
+            <p>
+              Latest build for <b>${{ github.repository }}</b> completed successfully
+              and is ready for <b>Production Approval</b>.
+            </p>
+
+            <h3 style="color:#0b5ed7;">Deployment Summary</h3>
+
+            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse; width:100%;">
+              <tr><td><b>Repository</b></td><td>${{ github.repository }}</td></tr>
+              <tr><td><b>Branch</b></td><td>${{ github.ref_name }}</td></tr>
+              <tr><td><b>Status</b></td><td style="color:green;"><b>SUCCESS</b></td></tr>
+              <tr><td><b>Triggered By</b></td><td>${{ github.actor }}</td></tr>
+              <tr><td><b>Commit ID</b></td><td>${{ github.sha }}</td></tr>
+              <tr><td><b>Commit Message</b></td><td>${{ needs.build.outputs.commit_message }}</td></tr>
+              <tr><td><b>Environment</b></td><td>Production</td></tr>
+            </table>
+
+            <br>
+
+            <h3 style="color:#0b5ed7;">Files Changed</h3>
+
+            <pre style="background:#f4f4f4;padding:12px;border:1px solid #ddd;border-radius:5px;">${{ needs.build.outputs.changed_files }}</pre>
+
+            <h3 style="color:#0b5ed7;">Approval Steps</h3>
+
+            <ol>
+              <li>Open GitHub Repository</li>
+              <li>Go to Actions</li>
+              <li>Select latest workflow</li>
+              <li>Click Review Deployments</li>
+              <li>Approve and Deploy</li>
+            </ol>
+
+            <p>
+              <b>Production URL:</b><br>
+              https://mywebsite-759899501179.us-central1.run.app/
+            </p>
+
+            <br>
+
+            <p>
+              Regards,<br>
+              <b>DevOps Automation Team</b>
+            </p>
+
+            </body>
+            </html>
+
+# =================================================
+# JOB 3 - MANUAL APPROVAL
+# =================================================
+  approval:
+    name: Production Approval
+    needs: approval-mail
+    runs-on: ubuntu-latest
+
+    environment:
+      name: production
+      url: https://YOUR_GCP_CLOUD_RUN_URL
+
+    steps:
+      - run: echo "Waiting for manager approval..."
+
+# -------------------------------------------------
+# JOB 4 - DEPLOY TO GCP CLOUD RUN
+# -------------------------------------------------
+  deploy:
+    needs: manual-approval
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v5
+
+      - name: Authenticate to GCP
+        uses: google-github-actions/auth@v2
         with:
           workload_identity_provider: projects/759899501179/locations/global/workloadIdentityPools/github-pool/providers/github-provider
           service_account: github-actions@githubaction-deploy-staticcode.iam.gserviceaccount.com
 
-      - uses: google-github-actions/setup-gcloud@v2
+      - name: Setup gcloud
+        uses: google-github-actions/setup-gcloud@v2
 
-      - run: gcloud auth configure-docker us-docker.pkg.dev --quiet
+      - name: Configure Docker
+        run: gcloud auth configure-docker us-docker.pkg.dev --quiet
 
-      - run: |
+      - name: Create Dockerfile
+        run: |
           cat <<EOF > Dockerfile
           FROM nginx:alpine
           COPY . /usr/share/nginx/html
@@ -39,13 +180,85 @@ jobs:
           CMD ["nginx", "-g", "daemon off;"]
           EOF
 
-      - run: docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }} .
+      - name: Build Docker Image
+        run: docker build -t us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }} .
 
-      - run: docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }}
+      - name: Push Docker Image
+        run: docker push us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }}
 
-      - run: |
+      - name: Deploy to Cloud Run
+        run: |
           gcloud run deploy ${{ env.SERVICE_NAME }} \
           --image us-docker.pkg.dev/${{ env.PROJECT_ID }}/myrepo/${{ env.SERVICE_NAME }} \
           --region ${{ env.REGION }} \
           --platform managed \
           --allow-unauthenticated
+
+# =================================================
+# JOB 5 - POST DEPLOYMENT EMAIL
+# =================================================
+  success-mail:
+    name: Send Success Email
+    needs: [deploy, build]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Send Success Mail
+        uses: dawidd6/action-send-mail@v3
+        with:
+          server_address: smtp.gmail.com
+          server_port: 587
+          secure: false
+          username: ${{ secrets.MAIL_USERNAME }}
+          password: ${{ secrets.MAIL_PASSWORD }}
+
+          subject: Production Deployment Successful | ${{ github.repository }}
+
+          to: ${{ env.MANAGER_EMAIL }}
+          from: ${{ secrets.MAIL_USERNAME }}
+
+          html_body: |
+            <html>
+            <body style="font-family:Arial, Helvetica, sans-serif; color:#333333; line-height:1.6;">
+
+            <h2 style="color:#198754;">Production Deployment Successful</h2>
+
+            <p>Dear <b>${{ env.MANAGER_NAME }}</b>,</p>
+
+            <p>
+            Approved production deployment for
+            <b>${{ github.repository }}</b> completed successfully.
+            </p>
+
+            <h3 style="color:#198754;">Deployment Summary</h3>
+
+            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse:collapse; width:100%;">
+              <tr><td><b>Repository</b></td><td>${{ github.repository }}</td></tr>
+              <tr><td><b>Branch</b></td><td>${{ github.ref_name }}</td></tr>
+              <tr><td><b>Status</b></td><td style="color:green;"><b>SUCCESSFUL</b></td></tr>
+              <tr><td><b>Approved By</b></td><td>${{ env.MANAGER_NAME }}</td></tr>
+              <tr><td><b>Executed By</b></td><td>${{ github.actor }}</td></tr>
+              <tr><td><b>Commit ID</b></td><td>${{ github.sha }}</td></tr>
+              <tr><td><b>Commit Message</b></td><td>${{ needs.build.outputs.commit_message }}</td></tr>
+            </table>
+
+            <br>
+
+            <h3 style="color:#198754;">Released Changes</h3>
+
+            <pre style="background:#f8f9fa;padding:14px;border:1px solid #ddd;border-radius:6px;">${{ needs.build.outputs.changed_files }}</pre>
+
+            <p>
+              <b>Production URL:</b><br>
+              https://mywebsite-759899501179.us-central1.run.app/
+            </p>
+
+            <br>
+
+            <p>
+              Regards,<br>
+              <b>DevOps Automation Team</b>
+            </p>
+
+            </body>
+            </html>
